# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Qt2\Tools\CMake_64\bin\cmake.exe

# The command to remove a file.
RM = C:\Qt2\Tools\CMake_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\sadfi\OneDrive\Bureau\Jardin d'enfant\jardindefant\jarinDenfant3"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\sadfi\OneDrive\Bureau\Jardin d'enfant\jardindefant\jarinDenfant3"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:\Qt2\Tools\CMake_64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\Qt2\Tools\CMake_64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\sadfi\OneDrive\Bureau\Jardin d'enfant\jardindefant\jarinDenfant3\CMakeFiles" "C:\Users\sadfi\OneDrive\Bureau\Jardin d'enfant\jardindefant\jarinDenfant3\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\sadfi\OneDrive\Bureau\Jardin d'enfant\jardindefant\jarinDenfant3\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jarinDenfant3

# Build rule for target.
jarinDenfant3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 jarinDenfant3
.PHONY : jarinDenfant3

# fast build rule for target.
jarinDenfant3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/build
.PHONY : jarinDenfant3/fast

#=============================================================================
# Target rules for targets named jarinDenfant3_autogen

# Build rule for target.
jarinDenfant3_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 jarinDenfant3_autogen
.PHONY : jarinDenfant3_autogen

# fast build rule for target.
jarinDenfant3_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3_autogen.dir\build.make CMakeFiles/jarinDenfant3_autogen.dir/build
.PHONY : jarinDenfant3_autogen/fast

eleve.obj: eleve.cpp.obj
.PHONY : eleve.obj

# target to build an object file
eleve.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/eleve.cpp.obj
.PHONY : eleve.cpp.obj

eleve.i: eleve.cpp.i
.PHONY : eleve.i

# target to preprocess a source file
eleve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/eleve.cpp.i
.PHONY : eleve.cpp.i

eleve.s: eleve.cpp.s
.PHONY : eleve.s

# target to generate assembly for a file
eleve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/eleve.cpp.s
.PHONY : eleve.cpp.s

enseignant.obj: enseignant.cpp.obj
.PHONY : enseignant.obj

# target to build an object file
enseignant.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/enseignant.cpp.obj
.PHONY : enseignant.cpp.obj

enseignant.i: enseignant.cpp.i
.PHONY : enseignant.i

# target to preprocess a source file
enseignant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/enseignant.cpp.i
.PHONY : enseignant.cpp.i

enseignant.s: enseignant.cpp.s
.PHONY : enseignant.s

# target to generate assembly for a file
enseignant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/enseignant.cpp.s
.PHONY : enseignant.cpp.s

jarinDenfant3_autogen/EWIEGA46WW/qrc_images.obj: jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.obj
.PHONY : jarinDenfant3_autogen/EWIEGA46WW/qrc_images.obj

# target to build an object file
jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.obj
.PHONY : jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.obj

jarinDenfant3_autogen/EWIEGA46WW/qrc_images.i: jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.i
.PHONY : jarinDenfant3_autogen/EWIEGA46WW/qrc_images.i

# target to preprocess a source file
jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.i
.PHONY : jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.i

jarinDenfant3_autogen/EWIEGA46WW/qrc_images.s: jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.s
.PHONY : jarinDenfant3_autogen/EWIEGA46WW/qrc_images.s

# target to generate assembly for a file
jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.s
.PHONY : jarinDenfant3_autogen/EWIEGA46WW/qrc_images.cpp.s

jarinDenfant3_autogen/mocs_compilation.obj: jarinDenfant3_autogen/mocs_compilation.cpp.obj
.PHONY : jarinDenfant3_autogen/mocs_compilation.obj

# target to build an object file
jarinDenfant3_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/jarinDenfant3_autogen/mocs_compilation.cpp.obj
.PHONY : jarinDenfant3_autogen/mocs_compilation.cpp.obj

jarinDenfant3_autogen/mocs_compilation.i: jarinDenfant3_autogen/mocs_compilation.cpp.i
.PHONY : jarinDenfant3_autogen/mocs_compilation.i

# target to preprocess a source file
jarinDenfant3_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/jarinDenfant3_autogen/mocs_compilation.cpp.i
.PHONY : jarinDenfant3_autogen/mocs_compilation.cpp.i

jarinDenfant3_autogen/mocs_compilation.s: jarinDenfant3_autogen/mocs_compilation.cpp.s
.PHONY : jarinDenfant3_autogen/mocs_compilation.s

# target to generate assembly for a file
jarinDenfant3_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/jarinDenfant3_autogen/mocs_compilation.cpp.s
.PHONY : jarinDenfant3_autogen/mocs_compilation.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.obj: mainwindow.cpp.obj
.PHONY : mainwindow.obj

# target to build an object file
mainwindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/mainwindow.cpp.obj
.PHONY : mainwindow.cpp.obj

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jarinDenfant3.dir\build.make CMakeFiles/jarinDenfant3.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... jarinDenfant3_autogen
	@echo ... jarinDenfant3
	@echo ... eleve.obj
	@echo ... eleve.i
	@echo ... eleve.s
	@echo ... enseignant.obj
	@echo ... enseignant.i
	@echo ... enseignant.s
	@echo ... jarinDenfant3_autogen/EWIEGA46WW/qrc_images.obj
	@echo ... jarinDenfant3_autogen/EWIEGA46WW/qrc_images.i
	@echo ... jarinDenfant3_autogen/EWIEGA46WW/qrc_images.s
	@echo ... jarinDenfant3_autogen/mocs_compilation.obj
	@echo ... jarinDenfant3_autogen/mocs_compilation.i
	@echo ... jarinDenfant3_autogen/mocs_compilation.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... mainwindow.obj
	@echo ... mainwindow.i
	@echo ... mainwindow.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

